#!/usr/local/bin/bash

exe=$(echo $0 | sed "s/.*\\/\(.*\)/\\1/g")
path=$(pwd)

usage() {
	echo "usage: ${exe} manga_name [scan_number=latest] [path=.]" >&2
}

if [[ -z "${1}" ]]; then
	usage
	exit 1
fi

if [[ ! -z "${3}" ]]; then
	if [[ -d "${3}" ]]; then
		path="${3}"
	else
		echo "${exe}: ${3}: Not a directory" >&2
		exit 1
	fi
fi

declare -A aliases

aliases["op"]="One Piece"
aliases["onepiece"]="One Piece"

aliases["opm"]="One Punch Man"
aliases["onepunchman"]="One Punch Man"

aliases["nrt"]="Naruto"
aliases["naruto"]="Naruto"

aliases["ft"]="Fairy Tail"
aliases["fairytail"]="Fairy Tail"

aliases["hh"]="Hunter X Hunter"
aliases["hxh"]="Hunter X Hunter"
aliases["hunter"]="Hunter X Hunter"
aliases["hunterhunter"]="Hunter X Hunter"
aliases["hunterxhunter"]="Hunter X Hunter"

aliases["nnt"]="Nanatsu No Taizai"
aliases["nanatsu"]="Nanatsu No Taizai"
aliases["taizai"]="Nanatsu No Taizai"
aliases["nanatsunotaizai"]="Nanatsu No Taizai"

aliases["aot"]="Shingeki No Kyojin"
aliases["adt"]="Shingeki No Kyojin"
aliases["ladt"]="Shingeki No Kyojin"
aliases["snk"]="Shingeki No Kyojin"
aliases["attackontitan"]="Shingeki No Kyojin"
aliases["attaquedestitans"]="Shingeki No Kyojin"
aliases["lattaquedestitans"]="Shingeki No Kyojin"
aliases["shingekinokyojin"]="Shingeki No Kyojin"

aliases["mha"]="My Hero Academia"
aliases["bnha"]="My Hero Academia"
aliases["heroacademia"]="My Hero Academia"
aliases["myheroacademia"]="My Hero Academia"
aliases["bokunoheroacademia"]="My Hero Academia"

aliases["berserk"]="Berserk"

aliases["fw"]="Shokugeki No Soma"
aliases["sns"]="Shokugeki No Soma"
aliases["foodwars"]="Shokugeki No Soma"
aliases["shokugekinosoma"]="Shokugeki No Soma"
aliases["shokugekinosouma"]="Shokugeki No Soma"

aliases["magi"]="Magi"

aliases["bc"]="Black Clover"
aliases["blackclover"]="Black Clover"

aliases["bleach"]="Bleach"

aliases["tg"]="The Gamer"
aliases["gamer"]="The Gamer"
aliases["thegamer"]="The Gamer"

name=$(echo "${1}" | sed "s/[ -_.'\"\(\)\{\}\[\]]//g" | tr '[:upper:]' '[:lower:]')
name="${aliases[${name}]}"

if [[ -z "${name}" ]]; then
	name="${1}"
fi

base=("http://www.japscan.com")
url=("http://www.japscan.com/lecture-en-ligne/\${name}/\${chapter}/\${n}.html")

latest() {
	arg=$(echo "${1}" | tr '[:upper:]' '[:lower:]' | sed "s/ /-/g")
	last=$(curl -s "http://www.japscan.com/mangas/${arg}/" 2>/dev/null | grep "//www.japscan.com/lecture-en-ligne/${arg}/" | head -n 2 | tail -n 1 | sed "s/.*href=\"[^\"]*\/\([0-9]*\)\/\".*/\1/")
	echo $last
}

getimgurl() {
	name=$(echo "${1}" | tr '[:upper:]' '[:lower:]' | sed "s/ /-/g")
	chapter="${2}"
	n="${3}"
	curl -s $(eval echo "${url}") | grep -A1 "id=\"img_link\"" | tail -n 1 | sed "s/.*src=\"\([^\"]*\)\".*/\\1/"

	if [[ "${n}" -eq 1 ]]; then
		warning=$(curl -s $(eval echo "${url}") | grep "id=\"note_chapitre\"" | sed "s/.*id=\"note_chapitre\">\([^<]*\).*/\\1/")
	fi
}

chapter="${2}"

if [[ -z "${2}" ]] || ! [[ "${2}" =~ ^[0-9]*$ ]]; then
	chapter=$(latest "${name}")
fi

if [[ -d "${path}/${name}/${chapter}" ]]; then
	echo "Chapter n°${chapter} of ${name} already downloaded."
	exit 1
fi

page=0
mkdir -p "${path}/${name}/${chapter}/"

while true; do
	page=$(( page + 1 ))
	imgurl=$(getimgurl "${name}" "${chapter}" "${page}")
	if [[ -z "${imgurl}" ]]; then
		exit;
	else
		ext=$(echo "${imgurl}" | sed "s/.*\\.\([^\\.]*.*\)$/\\1/")
		if [[ "${imgurl:0:1}" = "/" ]]; then
			imgurl="${base}${imgurl}"
		fi
		echo "Downloading ${name} chapter ${chapter} page ${page} to ${path}/${name}/${chapter}/${page}.${ext} ..."
		curl -s "${imgurl}" > "${path}/${name}/${chapter}/${page}.${ext}"
	fi
done
